# **EVENTS CHECK & CONTEXT**

In [13]:
import pandas as pd

events = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\raw\ufc_events.csv")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

events["event_date"] = pd.to_datetime(events["event_date"], errors="coerce")

events["event_date"] = events["event_date"].dt.strftime("%m/%d/%Y")


print(events.columns)
events.head(3)

Index(['event_name', 'event_date', 'event_location', 'event_url', 'fight_url',
       'fighter1', 'fighter1_url', 'fighter2', 'fighter2_url', 'result_raw',
       'winner', 'kd_1', 'kd_2', 'str_1', 'str_2', 'td_1', 'td_2', 'sub_1',
       'sub_2', 'weight_class', 'method', 'method_detail', 'round', 'time'],
      dtype='str')

,event_name,event_date,event_location,event_url,fight_url,fighter1,fighter1_url,fighter2,fighter2_url,result_raw,winner,kd_1,kd_2,str_1,str_2,td_1,td_2,sub_1,sub_2,weight_class,method,method_detail,round,time
0,UFC Fight Night: Fiziev vs. Torres,06/27/2026,"Baku, Azerbaijan",http://ufcstats.com/event-details/31e1ea6fe6b682f8,http://ufcstats.com/fight-details/c13dc0cccef263f7,Rafael Fiziev,http://ufcstats.com/fighter-details/c814b4c899793af6,Manuel Torres,http://ufcstats.com/fighter-details/2e7878927067fdca,win,Rafael Fiziev,1,0,25,22,2,0,0,0,Lightweight,KO/TKO,Punches,2,0:15
1,UFC Fight Night: Fiziev vs. Torres,06/27/2026,"Baku, Azerbaijan",http://ufcstats.com/event-details/31e1ea6fe6b682f8,http://ufcstats.com/fight-details/012c307c9d446c4d,Shara Magomedov,http://ufcstats.com/fighter-details/06734ca9d88dec3a,Michel Pereira,http://ufcstats.com/fighter-details/595db60957de51d3,win,Shara Magomedov,0,1,52,35,0,0,0,0,Middleweight,U-DEC,NaN,3,5:00
2,UFC Fight Night: Fiziev vs. Torres,06/27/2026,"Baku, Azerbaijan",http://ufcstats.com/event-details/31e1ea6fe6b682f8,http://ufcstats.com/fight-details/809814f03ff3140c,Matheus Camilo,http://ufcstats.com/fighter-details/72f890c5d421e705,Nazim Sadykhov,http://ufcstats.com/fighter-details/ff62013d2fce6d13,win,Matheus Camilo,1,0,4,0,0,0,0,0,Lightweight,KO/TKO,Punch,1,1:31

## CATEGORICAL COLUMNS CHECK

In [14]:
#result_raw weight_class	method	method_detail	round	
print(f"Result types ({(events['result_raw'].nunique())}): {list(events['result_raw'].unique())}")
print(f"Weight types ({(events['weight_class'].nunique())}): {list(events['weight_class'].unique())}")
print(f"Method types ({(events['method'].nunique())}): {list(events['method'].unique())}")
print(f"Method Detail types ({(events['method_detail'].nunique())}): {list(events['method_detail'].unique())}")
print(f"Round types ({(events['round'].nunique())}): {list(events['round'].unique())}")
print(f"Latest Event: {(events['event_date'].max())}")
print(f"Earliest Event: {(events['event_date'].min())}")
print(f"\n          NULL VALUES\n{events.isna().sum()}")

Result types (3): ['win', 'nc/nc', 'draw/draw']
Weight types (13): ['Lightweight', 'Middleweight', 'Flyweight', 'Welterweight', 'Light Heavyweight', 'Featherweight', 'Bantamweight', "Women's Bantamweight", 'Heavyweight', 'Catch Weight', "Women's Flyweight", "Women's Strawweight", "Women's Featherweight"]
Method types (8): ['KO/TKO', 'U-DEC', 'SUB', 'S-DEC', 'CNC', 'M-DEC', 'Overturned', 'DQ']
Method Detail types (40): ['Punches', nan, 'Punch', 'Suloev Stretch', 'Guillotine Choke', 'Rear Naked Choke', 'Arm Triangle', 'Twister', 'Elbows', 'Armbar', 'Kick', 'Knee', 'Calf Slicer', 'Heel Hook', "D'Arce Choke", 'Anaconda Choke', 'Knees', 'Spinning Back Kick', 'Neck Crank', 'Spinning Back Fist', 'Kimura', 'Elbow', 'Ezekiel Choke', 'Spinning Back Elbow', 'Triangle Choke', 'Slam', 'Keylock', 'Flying Knee', 'Triangle Armbar', 'Kicks', 'Other - Lock', 'Kneebar', 'Inverted Triangle', 'Von Flue Choke', 'Scarf Hold', 'Straight Armbar', 'Ankle Lock', 'Forearm Choke', 'Injury', 'Peruvian Necktie', 'Schultz Front Headlock']
Round types (5): [2, 3, 1, 4, 5]
Latest Event: 12/21/2019
Earliest Event: 01/11/2025

          NULL VALUES
event_name           0
event_date           0
event_location       0
event_url            0
fight_url            0
fighter1             0
fighter1_url         0
fighter2             0
fighter2_url         0
result_raw           0
winner              71
kd_1                 0
kd_2                 0
str_1                0
str_2                0
td_1                 0
td_2                 0
sub_1                0
sub_2                0
weight_class         0
method               0
method_detail     1949
round                0
time                 0
dtype: int64

### CHECK OF NULL VALUES

In [15]:
null_detail = events[events["method_detail"].isnull()]
print(f"Method types ({(null_detail['method'].nunique())}): {list(null_detail['method'].unique())}")
null_detail.head(3)

Method types (7): ['U-DEC', 'S-DEC', 'KO/TKO', 'CNC', 'M-DEC', 'Overturned', 'DQ']

,event_name,event_date,event_location,event_url,fight_url,fighter1,fighter1_url,fighter2,fighter2_url,result_raw,winner,kd_1,kd_2,str_1,str_2,td_1,td_2,sub_1,sub_2,weight_class,method,method_detail,round,time
1,UFC Fight Night: Fiziev vs. Torres,06/27/2026,"Baku, Azerbaijan",http://ufcstats.com/event-details/31e1ea6fe6b682f8,http://ufcstats.com/fight-details/012c307c9d446c4d,Shara Magomedov,http://ufcstats.com/fighter-details/06734ca9d88dec3a,Michel Pereira,http://ufcstats.com/fighter-details/595db60957de51d3,win,Shara Magomedov,0,1,52,35,0,0,0,0,Middleweight,U-DEC,NaN,3,5:00
4,UFC Fight Night: Fiziev vs. Torres,06/27/2026,"Baku, Azerbaijan",http://ufcstats.com/event-details/31e1ea6fe6b682f8,http://ufcstats.com/fight-details/d83294b031502177,Ikram Aliskerov,http://ufcstats.com/fighter-details/b07aed698fba8624,Brunno Ferreira,http://ufcstats.com/fighter-details/1e719d4b676dc19a,win,Ikram Aliskerov,0,0,47,19,5,0,1,0,Middleweight,U-DEC,NaN,3,5:00
6,UFC Fight Night: Fiziev vs. Torres,06/27/2026,"Baku, Azerbaijan",http://ufcstats.com/event-details/31e1ea6fe6b682f8,http://ufcstats.com/fight-details/6a35ff33b8597904,Farman Hasanov,http://ufcstats.com/fighter-details/c88f8a9c1ea7165d,Eric Nolan,http://ufcstats.com/fighter-details/64b12fe31be7560c,win,Farman Hasanov,0,0,21,15,17,0,0,0,Welterweight,U-DEC,NaN,3,5:00

In [16]:
null_winner = events[events["winner"].isnull() ]#& (events["result_raw"]=="nc/nc")]
print(f"Method types ({(null_winner['method'].nunique())}): {list(null_winner['method'].unique())}")
print(f"Result types ({(null_winner['result_raw'].nunique())}): {list(null_winner['result_raw'].unique())}")
null_winner.head(3)

Method types (5): ['CNC', 'M-DEC', 'Overturned', 'U-DEC', 'S-DEC']
Result types (2): ['nc/nc', 'draw/draw']

,event_name,event_date,event_location,event_url,fight_url,fighter1,fighter1_url,fighter2,fighter2_url,result_raw,winner,kd_1,kd_2,str_1,str_2,td_1,td_2,sub_1,sub_2,weight_class,method,method_detail,round,time
49,UFC Fight Night: Song vs. Figueiredo,05/30/2026,"Macau, China",http://ufcstats.com/event-details/1e75e6c9de99fa76,http://ufcstats.com/fight-details/7e8749cbf32ef1f8,Alex Perez,http://ufcstats.com/fighter-details/ab2b4ff41d6ebe0f,Sumudaerji,http://ufcstats.com/fighter-details/3cf18e01cb6cbde3,nc/nc,NaN,0,1,9,26,0,1,1,0,Flyweight,CNC,NaN,2,1:45
119,UFC Fight Night: Burns vs. Malott,04/18/2026,"Winnipeg, Manitoba, Canada",http://ufcstats.com/event-details/c3ac8d0da7b05772,http://ufcstats.com/fight-details/552f7cdaf93e1055,John Castaneda,http://ufcstats.com/fighter-details/5fa2974cbd18e05c,Mark Vologdin,http://ufcstats.com/fighter-details/0e6b611451a9a7d8,draw/draw,NaN,0,0,135,91,0,1,0,0,Catch Weight,M-DEC,NaN,3,5:00
130,UFC 327: Prochazka vs. Ulberg,04/11/2026,"Miami, Florida, USA",http://ufcstats.com/event-details/f3eb664db7fb1df3,http://ufcstats.com/fight-details/81d20c833e9a76eb,Chris Padilla,http://ufcstats.com/fighter-details/06626b6287e1ae1e,MarQuel Mederos,http://ufcstats.com/fighter-details/e2be0c1a9b886d92,draw/draw,NaN,0,0,147,112,1,1,0,0,Lightweight,M-DEC,NaN,3,5:00

#### CONTEXT OF NULL VALUES

##### * NULL DETAILS - FIGHT WENT WITHOUT EXTRA REQ. DATA BESIDES ***-METHOD-***
##### * NULL WINNER  - FIGHT WENT DRAW/DRAW OR ARE NC/NC (NO CONTEST - fight occured but was stopped due to a fighter being fauled/injured or not passing tests)

# **EVENTS LIST**

In [17]:
fights_list = events[["event_name","event_date","fight_url"]].drop_duplicates()

fights_list.to_csv(r"C:\Git projects\ufc_ml\ufc_data\lists\list_fights.csv", index=False)

fights_list

,event_name,event_date,fight_url
0,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/c13dc0cccef263f7
1,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/012c307c9d446c4d
2,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/809814f03ff3140c
3,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/81cde317c156723b
4,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/d83294b031502177
...,...,...,...
3697,UFC Fight Night: Barboza vs. Gaethje,03/30/2019,http://ufcstats.com/fight-details/6173056f0e080ca6
3698,UFC Fight Night: Barboza vs. Gaethje,03/30/2019,http://ufcstats.com/fight-details/7dc3ada8f2135477
3699,UFC Fight Night: Barboza vs. Gaethje,03/30/2019,http://ufcstats.com/fight-details/93a081342561d0c3
3700,UFC Fight Night: Barboza vs. Gaethje,03/30/2019,http://ufcstats.com/fight-details/b695fc80bd538172
3701,UFC Fight Night: Barboza vs. Gaethje,03/30/2019,http://ufcstats.com/fight-details/3db15d45e8490c22

# **FIGHTERS LIST**

In [18]:

fighters = events[["fighter1","fighter1_url","fighter2","fighter2_url"]]

part1 = fighters[["fighter1", "fighter1_url"]].rename(
    columns={"fighter1": "fighter", "fighter1_url": "fighter_url"}
)

part2 = fighters[["fighter2", "fighter2_url"]].rename(
    columns={"fighter2": "fighter", "fighter2_url": "fighter_url"}
)

fighters = pd.concat([part1, part2], ignore_index=True)

fighters = fighters.drop_duplicates(ignore_index=True)

pd.set_option('display.max_colwidth', None)

fighters.to_csv(r"C:\Git projects\ufc_ml\ufc_data\lists\list_fighters.csv", index=False)
(fighters)

               fighter                                           fighter_url
0        Rafael Fiziev  http://ufcstats.com/fighter-details/c814b4c899793af6
1      Shara Magomedov  http://ufcstats.com/fighter-details/06734ca9d88dec3a
2       Matheus Camilo  http://ufcstats.com/fighter-details/72f890c5d421e705
3        Asu Almabayev  http://ufcstats.com/fighter-details/8d3273573b85be09
4      Ikram Aliskerov  http://ufcstats.com/fighter-details/b07aed698fba8624
...                ...                                                   ...
1328       Wilson Reis  http://ufcstats.com/fighter-details/5aedf14771ca82d2
1329  Curtis Millender  http://ufcstats.com/fighter-details/f1928a52590c5532
1330      David Branch  http://ufcstats.com/fighter-details/d2c55d1d2e67773b
1331   Jessica Aguilar  http://ufcstats.com/fighter-details/8f382b3baa954d2a
1332      Ross Pearson  http://ufcstats.com/fighter-details/4f732e58ed907eff

[1333 rows x 2 columns]