In [14]:
import pandas as pd

fighters = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\slv\data_stats_fighters.csv")
display(fighters)
events = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\lists\list_fights.csv")
display(events)
fight_stats = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\fight_details_clean.csv")
display(fight_stats)

,fighter,Height,Weight,Reach,STANCE,DOB,SLpM,Str. Acc.,SApM,Str. Def,TD Avg.,TD Acc.,TD Def.,Sub. Avg.
0,Rafael Fiziev,"5' 8""",155 lbs.,"71""",Switch,03/05/1993,4.71,52%,4.81,50%,1.00,71%,90%,0.0
1,Shara Magomedov,"6' 2""",185 lbs.,"73""",Orthodox,05/16/1994,5.55,62%,3.62,45%,0.00,0%,73%,0.0
2,Matheus Camilo,"5' 10""",155 lbs.,"69""",Orthodox,01/02/2001,2.22,43%,3.05,66%,4.16,53%,0%,0.6
3,Asu Almabayev,"5' 4""",125 lbs.,"65""",Orthodox,01/25/1994,2.28,51%,1.94,53%,4.74,45%,44%,1.4
4,Ikram Aliskerov,"6' 0""",185 lbs.,"76""",Southpaw,12/07/1992,5.56,60%,4.01,45%,3.82,68%,100%,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,Mauricio Rua,"6' 1""",205 lbs.,"76""",Orthodox,11/25/1981,3.57,50%,2.79,54%,2.01,48%,49%,0.7
939,Mounir Lazzez,"6' 1""",170 lbs.,"76""",Orthodox,11/16/1987,7.49,55%,5.42,53%,1.80,57%,71%,0.0
940,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,09/02/1981,2.41,44%,3.02,55%,1.01,23%,45%,0.1
941,Cheyanne Vlismas,"5' 3""",115 lbs.,"63""",Switch,06/25/1995,4.93,50%,2.57,64%,0.25,33%,66%,0.2
942,Saidyokub Kakhramonov,"5' 8""",135 lbs.,"69""",Orthodox,11/14/1995,2.05,51%,0.88,58%,6.63,48%,83%,1.9

,event_name,event_date,fight_url
0,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/c13dc0cccef2...
1,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/012c307c9d44...
2,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/809814f03ff3...
3,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/81cde317c156...
4,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/d83294b03150...
...,...,...,...
1829,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/ed6203e849a2...
1830,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/efc64d8aae56...
1831,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/8f00da6ea818...
1832,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/f87a7812733f...
1833,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/ccb7e2851319...

,event_name,fighter_f1,fighter_f2,outcome_f1,outcome_f2,bout_type,title,method,round,tot_fight_time,...,sg_strk_r5_body_f1,sg_strk_r5_body_f2,sg_strk_r5_leg_f1,sg_strk_r5_leg_f2,sg_strk_r5_distance_f1,sg_strk_r5_distance_f2,sg_strk_r5_clinch_f1,sg_strk_r5_clinch_f2,sg_strk_r5_grf1,sg_strk_r5_grf2
0,UFC Fight Night: Fiziev vs. Torres,Shara Magomedov,Michel Pereira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UFC Fight Night: Fiziev vs. Torres,Nazim Sadykhov,Matheus Camilo,0,1,Lightweight Bout,0,KO/TKO,1,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UFC Fight Night: Fiziev vs. Torres,Asu Almabayev,Charles Johnson,1,0,Flyweight Bout,0,Submission,3,813,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UFC Fight Night: Fiziev vs. Torres,Ikram Aliskerov,Brunno Ferreira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UFC Fight Night: Fiziev vs. Torres,Abus Magomedov,Michal Oleksiejczuk,1,0,Middleweight Bout,0,Submission,1,205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829,UFC Fight Night: Cannonier vs. Strickland,Bryan Battle,Rinat Fakhretdinov,0,1,Welterweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1830,UFC Fight Night: Cannonier vs. Strickland,David Dvorak,Manel Kape,0,1,Flyweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1831,UFC Fight Night: Cannonier vs. Strickland,Sergey Morozov,Journey Newson,1,0,Bantamweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1832,UFC Fight Night: Dolidze vs. Hernandez,Uros Medic,Gilbert Urbina,1,0,Welterweight Bout,0,KO/TKO,1,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1833,UFC Fight Night: Fiziev vs. Torres,Rafael Fiziev,Manuel Torres,1,0,Lightweight Bout,0,KO/TKO,2,315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fight_data = fight_stats.copy()
fight_data = fight_data.drop(columns=["event_date_x", "event_date_y", "event_date"], errors="ignore")

events_clean = events[["event_name", "event_date"]].drop_duplicates(subset=["event_name"], keep="first")
fight_data = fight_data.merge(events_clean, on="event_name", how="left")

fight_data = fight_data.merge(
    fighters.add_suffix("_f1"), 
    left_on="fighter_f1", 
    right_on="fighter_f1", 
    how="left"
)

fight_data = fight_data.merge(
    fighters.add_suffix("_f2"), 
    left_on="fighter_f2", 
    right_on="fighter_f2", 
    how="left"
)

display(fight_data)

,event_name,fighter_f1,fighter_f2,outcome_f1,outcome_f2,bout_type,title,method,round,tot_fight_time,...,STANCE_f2,DOB_f2,SLpM_f2,Str. Acc._f2,SApM_f2,Str. Def_f2,TD Avg._f2,TD Acc._f2,TD Def._f2,Sub. Avg._f2
0,UFC Fight Night: Fiziev vs. Torres,Shara Magomedov,Michel Pereira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,Orthodox,10/06/1993,4.28,51%,4.32,50%,1.11,52%,75%,0.6
1,UFC Fight Night: Fiziev vs. Torres,Nazim Sadykhov,Matheus Camilo,0,1,Lightweight Bout,0,KO/TKO,1,91,...,Orthodox,01/02/2001,2.22,43%,3.05,66%,4.16,53%,0%,0.6
2,UFC Fight Night: Fiziev vs. Torres,Asu Almabayev,Charles Johnson,1,0,Flyweight Bout,0,Submission,3,813,...,Switch,01/10/1991,4.54,49%,3.88,55%,0.47,16%,66%,0.4
3,UFC Fight Night: Fiziev vs. Torres,Ikram Aliskerov,Brunno Ferreira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,Orthodox,11/04/1992,3.27,49%,3.75,51%,1.00,22%,50%,0.6
4,UFC Fight Night: Fiziev vs. Torres,Abus Magomedov,Michal Oleksiejczuk,1,0,Middleweight Bout,0,Submission,1,205,...,Southpaw,02/22/1995,5.73,52%,4.45,60%,0.99,42%,52%,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1842,UFC Fight Night: Cannonier vs. Strickland,Bryan Battle,Rinat Fakhretdinov,0,1,Welterweight Bout,0,Decision - Unanimous,3,900,...,Orthodox,09/28/1991,5.03,52%,3.61,54%,3.91,34%,91%,0.2
1843,UFC Fight Night: Cannonier vs. Strickland,David Dvorak,Manel Kape,0,1,Flyweight Bout,0,Decision - Unanimous,3,900,...,Southpaw,11/14/1993,4.68,55%,3.88,57%,0.36,30%,78%,0.2
1844,UFC Fight Night: Cannonier vs. Strickland,Sergey Morozov,Journey Newson,1,0,Bantamweight Bout,0,Decision - Unanimous,3,900,...,Orthodox,03/07/1989,2.64,32%,2.57,64%,0.56,16%,43%,0.3
1845,UFC Fight Night: Dolidze vs. Hernandez,Uros Medic,Gilbert Urbina,1,0,Welterweight Bout,0,KO/TKO,1,63,...,Orthodox,04/05/1996,5.57,56%,4.62,44%,2.86,44%,0%,0.7
1846,UFC Fight Night: Fiziev vs. Torres,Rafael Fiziev,Manuel Torres,1,0,Lightweight Bout,0,KO/TKO,2,315,...,Switch,03/25/1995,6.57,56%,4.24,50%,1.32,66%,76%,0.7